#!/usr/bin/env bash
set -ex

export SETUPTOOLS_SCM_PRETEND_VERSION="${PKG_VERSION}"
export CMAKE_ARGS="${CMAKE_ARGS} -DCMAKE_FIND_FRAMEWORK:STRING=NEVER -DCMAKE_FIND_APPBUNDLE:STRING=NEVER -DENABLE_OPENMP:BOOL=ON -DENABLE_ARCH_FLAGS:BOOL=OFF -DFETCHCONTENT_FULLY_DISCONNECTED:BOOL=ON -DEigen3_ROOT:PATH=${PREFIX}"

"${PYTHON}" -m pip install . -vv --no-deps --no-build-isolation
