{% set name = "cppe" %}
{% set version = "0.3.2" %}
{% set sha256 = "962389811b11e20ffb0570fe458f0a36c4c1ef09a3ce0a0ae50d132812cd85b1" %}
{% set build = 1 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/maxscheurer/cppe/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  binary_relocation: true
  run_exports:
    - {{ pin_subpackage('cppe', max_pin='x.x') }}

requirements:
  build:
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - pybind11  # [build_platform != target_platform]
    - cmake >=3.5
    - {{ compiler('cxx') }}
    - ninja
    - llvm-openmp  # [osx or win]
    - libgomp      # [linux]
    - eigen
  host:
    - pybind11
    - pybind11-abi
    - python
  run:
    - python

test:
  requires:
    - pip
    - numpy
    - m2w64-binutils  # [win]   # provides objdump.exe
    - pytest
    - numpy
    - h5py  # [python_impl != "pypy"]
    - scipy
    - pandas
  imports:
    - cppe
  commands:
    # Verify Python extension library
    - test -f $SP_DIR/cppe/pycppe*.so                                       # [not win]
    - if not exist %PREFIX%\\Lib\\site-packages\\cppe\\pycppe.*.pyd exit 1  # [win]
    # Inspect linkage
    - ldd -v $SP_DIR/cppe/pycppe*.so  # [linux64]
    - otool -L $SP_DIR/cppe/pycppe*.so  # [osx]
    - objdump.exe -p %SP_DIR%\\cppe\\pycppe.*.pyd | findstr /i "dll"  # [win]
    - pip check
    - pytest --capture=no --log-cli-level=INFO --pyargs cppe -m "not needs_polarizationsolver"  # [python_impl != "pypy"]

about:
  home: https://github.com/maxscheurer/cppe
  dev_url: https://github.com/maxscheurer/cppe
  doc_url: https://cppe.readthedocs.io
  doc_source_url: https://github.com/maxscheurer/cppe/blob/master/doc/source/index.rst
  license: LGPL-3.0-or-later
  license_file: LICENSE
  license_url: https://opensource.org/licenses/LGPL-3.0
  license_family: LGPL
  summary: "C++ and Python library for Polarizable Embedding calculations"

extra:
  recipe-maintainers:
    - robertodr
    - maxscheurer
