{% set name = "cppe" %}
{% set version = "0.3.1" %}
{% set sha256 = "38d4230ba3ace78936049c23ad4b1fe9e704fd250ec57cc9733cb3904b62cf7c" %}
{% set build = 10 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

#source:
#  url: https://github.com/maxscheurer/cppe/archive/v{{ version }}.tar.gz
#  sha256: {{ sha256 }}

source:
  git_url: https://github.com/robertodr/cppe.git
  git_rev: patches-windows

build:
  number: {{ build }}
  binary_relocation: true
  run_exports:
    - {{ pin_subpackage('cppe', max_pin='x.x') }}

requirements:
  build:
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - pybind11  # [build_platform != target_platform]
    - cmake >=3.5
    - {{ compiler('cxx') }}
    - ninja
    - llvm-openmp  # [osx or win]
    - libgomp      # [linux]
    - eigen
  host:
    - pybind11
    - pybind11-abi
    - python
  run:
    - python

test:
  requires:
    - pip
    - numpy
    - m2w64-binutils  # [win]   # provides objdump.exe
  imports:
    - cppe
  commands:
    # Verify C++ library
    - test -f $PREFIX/lib/libcppe$SHLIB_EXT                 # [not win]
    - if not exist %PREFIX%\\bin\\cppe.dll exit 1  # [win]
    - if not exist %PREFIX%\\lib\\cppe.lib exit 1  # [win]
    # Inspect linkage
    - ldd -v $PREFIX/lib/libcppe$SHLIB_EXT        # [linux]
    - otool -L $PREFIX/lib/libcppe$SHLIB_EXT      # [osx]
    - objdump.exe -p %PREFIX%\\bin\\cppe.dll | findstr /i "dll"  # [win]
    # Verify Python extension library
    - test -f $SP_DIR/cppe/pycppe*.so                                       # [not win]
    - if not exist %PREFIX%\\Lib\\site-packages\\cppe\\pycppe.*.pyd exit 1  # [win]
    # Inspect linkage
    - ldd -v $SP_DIR/cppe/pycppe*.so  # [linux]
    - otool -L $SP_DIR/cppe/pycppe*.so  # [osx]
    - objdump.exe -p %SP_DIR%\\cppe\\pycppe.*.pyd | findstr /i "dll"  # [win]
    - pip check

about:
  home: https://github.com/maxscheurer/cppe
  dev_url: https://github.com/maxscheurer/cppe
  doc_url: https://cppe.readthedocs.io
  doc_source_url: https://github.com/maxscheurer/cppe/blob/master/doc/source/index.rst
  license: LGPL-3.0-or-later
  license_file: LICENSE
  license_url: https://opensource.org/licenses/LGPL-3.0
  license_family: LGPL
  summary: "C++ and Python library for Polarizable Embedding calculations"

extra:
  recipe-maintainers:
    - robertodr
    - maxscheurer
